# Generated by Django 3.2 on 2022-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220521_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='clothes',
            field=models.ManyToManyField(blank=True, to='app.Clothe'),
        ),
        migrations.AlterField(
            model_name='closet',
            name='outfits',
            field=models.ManyToManyField(blank=True, to='app.Outfit'),
        ),
    ]
