# Generated by Django 3.2 on 2022-05-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220521_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='app.Color'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='shoeStyle',
            field=models.ManyToManyField(blank=True, null=True, to='app.ShoeStyle'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='style',
            field=models.ManyToManyField(blank=True, null=True, to='app.Style'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.type'),
        ),
    ]
