# Generated by Django 3.2 on 2022-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220521_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='isFormal',
            field=models.BooleanField(blank=True, choices=[(True, '正式'), (False, '非正式')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='warmness',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, null=True),
        ),
    ]
