# Generated by Django 3.2 on 2022-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220521_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
