# Generated by Django 3.2 on 2022-05-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_clothe_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='app.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='isFormal',
            field=models.BooleanField(blank=True, choices=[(True, '正式'), (False, '休閒')], default=False, null=True),
        ),
    ]
