# Generated by Django 3.2 on 2022-06-20 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220620_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondHandPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondHandPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time', models.TimeField()),
                ('isProduct', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(blank=True, null=True, to='app.Comment')),
                ('likes', models.ManyToManyField(blank=True, related_name='secondHandLikes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followedSecondHandPosts',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='app.SecondHandPost'),
        ),
    ]
