# Generated by Django 3.2 on 2022-07-11 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220620_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondhandpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='amount',
        ),
        migrations.AddField(
            model_name='secondhandpost',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondhandpost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clothe'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.secondhandpost'),
        ),
        migrations.AlterField(
            model_name='secondhandpost',
            name='isProduct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='secondhandpost',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='SecondHandComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.secondhandpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.secondhandpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
