# Generated by Django 3.2 on 2022-07-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220711_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandpost',
            name='used',
            field=models.IntegerField(choices=[(1, 'Well-used'), (2, 'Used'), (3, 'New')], null=True),
        ),
        migrations.AlterField(
            model_name='secondhandpost',
            name='isProduct',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
