# Generated by Django 3.2 on 2022-07-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220711_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondhandpost',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
