# Generated by Django 3.2 on 2022-09-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_transactionlog_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
    ]
