# Generated by Django 3.2 on 2022-09-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_clothe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandpost',
            name='isSold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
