# Generated by Django 3.2 on 2022-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_clothe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clothes',
            field=models.ManyToManyField(blank=True, null=True, to='app.Clothe'),
        ),
    ]
