# Generated by Django 3.2 on 2022-09-05 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_bankaccount_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='app.wallet'),
        ),
    ]
