# Generated by Django 3.2 on 2022-09-21 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_bankaccount_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPath', models.TextField()),
                ('similarity_model', models.FileField(upload_to='models/<django.db.models.fields.TextField>')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
