# Generated by Django 3.2 on 2022-09-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_similaritymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='address',
            field=models.CharField(default='國立政治大學', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='payment',
            field=models.IntegerField(choices=[(1, '貨到付款'), (2, '錢包付款')], default=2),
            preserve_default=False,
        ),
    ]
