# Generated by Django 3.2 on 2022-09-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220921_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='buyer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bought_transaction', to='app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='done',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sold_transaction', to='app.user'),
            preserve_default=False,
        ),
    ]
